# Generated by Django 5.2.6 on 2026-02-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDiseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('whatsapp', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('texto_letrero', models.CharField(max_length=140)),
                ('tipo_neon', models.CharField(choices=[('primera', 'Primera Generacion'), ('segunda', 'Segunda Generacion'), ('pixel', 'Neon Pixel'), ('rayo', 'Neon Rayo'), ('rgb', 'Neon RGB')], max_length=20)),
                ('material', models.CharField(choices=[('mdf', 'MDF'), ('pvc', 'PVC'), ('acrilico', 'Acrilico')], max_length=20)),
                ('ancho_cm', models.PositiveIntegerField(default=60)),
                ('color', models.CharField(default='Blanco frio', max_length=30)),
                ('mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
