# Generated by Django 5.2.6 on 2026-02-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letreros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddiseno',
            name='color',
        ),
        migrations.AddField(
            model_name='solicituddiseno',
            name='alto_cm',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='solicituddiseno',
            name='color_figura',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='solicituddiseno',
            name='color_letras',
            field=models.CharField(default='Blanco frio', max_length=30),
        ),
        migrations.AddField(
            model_name='solicituddiseno',
            name='nivel_detalle',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=20),
        ),
        migrations.AddField(
            model_name='solicituddiseno',
            name='tipo_proyecto',
            field=models.CharField(choices=[('texto', 'Solo texto'), ('texto_figura', 'Texto + figura'), ('logo', 'Logo o ilustracion detallada')], default='texto', max_length=20),
        ),
        migrations.AddField(
            model_name='solicituddiseno',
            name='tipografia',
            field=models.CharField(choices=[('script', 'Script fluida'), ('bold', 'Bloque gruesa'), ('tech', 'Tecnica futurista'), ('classic', 'Clasica limpia')], default='script', max_length=20),
        ),
    ]
