# Generated by Django 5.2.6 on 2026-02-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letreros', '0002_remove_solicituddiseno_color_solicituddiseno_alto_cm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddiseno',
            name='color_figura',
        ),
        migrations.AlterField(
            model_name='solicituddiseno',
            name='color_letras',
            field=models.CharField(default='#ff4fd8', max_length=20),
        ),
    ]
